config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to: "homes#top"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 resources :books, only: [ :index, :create, :show, :edit, :update, :destroy]
 resources :users, only: [:index, :show, :edit, :update]
 get '/home/about' => 'homes#about', as: 'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user

#バリテーション
 validates :title, presence: true
 validates :body, presence: true, length: { maximum:200 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :books, dependent: :destroy
 
 validates :name, uniqueness: true, length: { minimum:2, maximum: 20 }
 validates :introduction, presence: false, length: { maximum:50 }
 
 has_one_attached :profile_image

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top, :about]
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]

  def index
   @book = Book.new
   @books = Book.all
   @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if  @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
   else
    @books = Book.all
    @user = current_user
    render :index
   end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
   else
    render :edit
   end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
   
  @book = Book.find(params[:id])
   user = @book.user
   unless user.id == current_user.id
       redirect_to books_path
   end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]
  
  def index
      @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
   @user = User.find(params[:id])
   if  @user.update(user_params)
   flash[:notice] = 'You have updated user successfully'
   redirect_to user_path
   else
    render :edit
   end
  end


  private

  def user_params
   params.require(:user).permit(:name,:profile_image,:introduction)
  end
 
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<!--部分テンプレート左側-->
   <h1>User info</h1>
<!--投稿者のshowへ遷移する-->
<%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
   <tbody>
    <tr></tr>
     <tr>
      <th>name</th>
      <th><%= user.name %></th>
     </tr>
     <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
   </tr>
   </tbody>
  </table>
  <div class="row">
<!--本人以外は編集できない-->

   <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block edit_user_path" do %>
  <i class="fas fa-user-cog"></i>
   <% end %>
   
  </div>

  <h2 class="mt-3">New book</h2>

  <%= form_with model: Book.new , url: books_path, method: :post do |f| %>
   <div class="form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title, class: 'form-control' %>
   </div>
   <div class="form-group">
    <%= f.label :body, 'Opinion' %>
    <%= f.text_area :body, class: 'form-control' %>
   </div>
   <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success' %>
   </div>
  <% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/dastroy.html.erb
<h1>Books#dastroy</h1>
<p>Find me in app/views/books/dastroy.html.erb</p>

app/views/books/edit.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
   <% if @book.errors.any? %>
<h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
 <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
 </ul>
 <% end %>
  <%= form_with model: @book do |f| %>
  <div class="form-group">
   <%= f.label :title, 'Title'  %>
   <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
   <%= f.label :opinion, 'Opinion'  %>
   <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
   <%= f.submit "Update Book", class:'btn btn-success' %>
  </div>
<% end %>

<%= link_to "Show", book_path(@book[:id]) %>|
<%= link_to "Back", books_path %>
</div>
</div>
     </div></main>

app/views/books/index.html.erb
<div class="container">
 <!--バリデーション,サクセスメッセージ-->
<div class="row">
 <div class="col-md-3">
 <% if @book.errors.any? %>
<h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
 <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
 </ul>
 <% end %>
  <%= render 'books/list', user:@user ,book:@book %>
 </div>
 <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
<table class="table table-hover table-inverse">
 <thead>
  <tr>
   <th></th>
   <th>Title</th>
   <th>Opinion</th>
  </tr>
 </thead>
 <tbody>
  <% @books.each do |book| %>
  <tr>
   <td><%= link_to user_path(book.user.id) do %> <%= image_tag @user.get_profile_image(80,80) %><% end %></td>
   <td><%= link_to book.title,book_path(book.id) %></td>
   <td><p><%= book.body %></p></td>
  </tr>
 <% end %>
 </tbody>
 </table>
 </div>
</div>

app/views/books/show.html.erb
<!--ユーザー情報などの部分テンプレート-->
<div class="container">
<div class="row">
 <div class="col-md-3">
<%= render 'books/list', user:@user ,book:@book %>
</div>

<div class="col-md-8 offset-md-1">
 <h2>Book detail</h2>
<table class="table table-hover table-inverse">
 <tobody>
 <tr>
  <td><%= image_tag @user.get_profile_image(80,80) %>
   <br><%= link_to @user[:name], user_path(@user[:id]) %>
     </td>

  <td><%= link_to @book[:title], book_path(@book[:id]) %></td>
  <td><%= @book.body %></td>
  <% if user_signed_in? && current_user.id == @book.user_id %>
  <div class="row">
  <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success edit_book_path(@book)" %></td>
  <td><%= link_to "Destroy", book_path(@book),  method: :delete ,data: {confirm: "本当に削除しますか？"}, class:"btn btn-sm btn-danger destroy_books_path"  %></td>
  </div>
 <% end %>
 </tr>
 </tobody>
</table>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/homes/about.html.erb
<%= flash[:notice] %>
<p id="notice"></p>
<div class="container">
  <div class="row">
   <h1 class="px-3 mx-auto">Welcome to<i class= "fas fa-book fa-lg"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p id="notice"></p>
<div class="container">
 <div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
 <h1>welcome to<i class= "fas fa-book fa-lg"></i>Bookers !!</h1>

<p>In<i class= "fas fa-book fa-lg"></i>Bookers,</br></p>
<p>you can share and exchange your opinions,inpressions,and emotions</br>
about various books!</p>


<div class="btn-wrapper col-10 mx-auto">
<div class="row">
<%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
</div>
<div class="row">
<%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
</div>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   <title>Bookers2</title>
  </head>

  <body>
   <header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li>
            <% if user_signed_in? %>
      <li>
       <%= link_to  user_path(current_user.id),class:'nav-link text-light' do %>
      <i class="fas fa-home color_white"></i>Home
      <% end %>
      </li>
      <li>
       <%= link_to users_path,class:'nav-link text-light' do %>
      <i class="fas fa-users"></i>Users
      <% end %>
      </li>
      <li>
       <%= link_to  books_path,class:'nav-link text-light' do %>
      <i class="fas fa-book-open"></i>Books
      <% end %>
      </li>
      <li>
       <%= link_to  destroy_user_session_path, method: :delete,class:'nav-link text-light' do %>
       <i class="fas fa-sign-out-alt"></i>Log out
      <% end %>
      </li>
    <% else %>
      <li>
       <%= link_to root_path,class:'nav-link text-light' do %>
       <i class="fas fa-home"></i>Home
      <% end %>
      </li>
       <li>
       <%= link_to about_path,class:'nav-link text-light' do %>
    <i class="fas fa-link"></i>About
       <% end %>
      </li>
      <li>
       <%= link_to new_user_registration_path,class:'nav-link text-light' do %>
       <i class="fas fa-user-plus"></i>Sign up
       <% end %>
      </li>
       <li>
      <%= link_to new_user_session_path,class:'nav-link text-light' do %>
       <i class="fas fa-sign-in-alt"></i>Log in
       <% end %>
      </li>

    <% end %>
        </ul>
      </div>
    </div>
  </nav>

  </header>
<main>
 <p id="notice"><%= flash[:notice] %></p>
     <%= yield %>
</main>

<footer>
 <div class='container mt-5'>
  <div class='row'>
   <div class='mx-auto w-25'>
    <p>CopyRight Infratop.inc</p>
   </div>
  </div>
 </div>
</footer>

  <!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>-->
  <!--<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>-->
  <!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>-->
</body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
 <%= @user.errors.count %>件のエラーが発生
 <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
 </ul>
 <% end %>

<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>

<%= form_with model: @user do |f| %>
  <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, placeholder:"名前", class: 'form-control' %>
  </div>

  <div class="form-group">
      <%= f.label :profile_image, 'Image' %>
      <%= f.file_field :profile_image, accept: "image/*", class: 'form-control-file' %>
  </div>

  <div class="form-group">
      <%= f.label :introduction, 'Introduction' %>
      <%= f.text_area :introduction, class: 'form-control' %>
  </div>

  <div class="form-group">
      <%= f.submit "Update User", class: 'btn btn-secondary' %>
  </div>
<% end %>
</div>
</div>

      </div></main>

app/views/users/index.html.erb
<!--部分テンプレートの追加-->
<div class="container px-5 px-sm-0 ">
<div class="row">
 <div class="col-md-3">
<%= render 'books/list', user: current_user , book: @book %>
</div>
<!--ユーザーの一覧-->
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
<table class="table">
  <thead>
   <tr>
     <th>image</th>
     <th>name</th>
     <th></th>
   </tr>
  </thead>
  <tbody>
  <% @user.each do |user| %>
  <tr>
    <td><%= image_tag user.get_profile_image(80,80) %></td>
    <td><p><%= user.name %></p></td>
    <td> <%= link_to "Show", user_path(user.id) %></td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>
</div>

app/views/users/show.html.erb
 <div class="container px-5 px-sm-0 ">
<div class="row">
 <div class="col-md-3">
<!-- ユーザーの詳細　部分テンプレート -->
<%= render 'books/list', user:@user ,book:@book %>
</div>
<!-- ユーザーの投稿一覧 右ページ-->
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
<table class="table table-hover table-inverse">
<thead>
 <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th colspan="3"></th>
 </tr>
 </thead>
 <tbody>
  <% @books.each do |books| %>
  <tr>
   <td><%= link_to user_path(books.user.id)  do %><%= image_tag books.user.get_profile_image(80,80) %><% end %></td>
   <td><%= link_to books[:title], book_path(books[:id])  %></td>
   <td><p><%= books.body %></p></td>
  </tr>
 <% end %>
 </tbody>
</table>
</div>
</div>